name = "technophilie"
license = "GPL-3.0"
licenselink = "https://github.com/tristanwagner/hugo-technophilie/raw/master/COPYING"
description = "A super minimalistic Hugo theme forked from hugo-kernal."
homepage = "https://github.com/tristanwagner/hugo-technophilie"
tags = ["minimal", "light", "dark", "blog"]
features = []
min_version = "0.41"

authors = [
    {name = "Tristan WAGNER", homepage = "technophilie.io"}
]

[original]
    author = "Siren"
    homepage = "siren.kernal.eu"
    repo = "https://gitlab.com/sausagenoods/hugo-node"
