name = "kernal"
license = "GPL-3.0"
licenselink = "https://gitlab.com/kernal/hugo-kernal/raw/master/COPYING"
description = "A super minimalistic Hugo theme."
homepage = "https://gitlab.com/kernal/hugo-kernal"
tags = ["minimal", "light", "dark", "blog"]
features = []
min_version = "0.41"

authors = [
    {name = "Siren", homepage = "siren.kernal.eu"},
    {name = "Stnby", homepage = "kernal.eu"}
]

[original]
    author = "Siren"
    homepage = "siren.kernal.eu"
    repo = "https://gitlab.com/sausagenoods/hugo-node"
