# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes

name = "kernal"
license = "MIT"
licenselink = "https://gitlab.com/kernal/hugo-kernal/raw/master/LICENSE"
description = "A super minimalistic Hugo theme."
homepage = "https://gitlab.com/kernal/hugo-kernal"
tags = ["minimal", "light", "blog"]
features = []
min_version = "0.41"

authors = [
    {name = "Siren", homepage = "siren.kernal.eu"},
    {name = "Stnby", homepage = "stnby.kernal.eu"}
]

[original]
    author = "Siren"
    homepage = "siren.kernal.eu"
    repo = "https://gitlab.com/sausagenoods/hugo-node"
